apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::882345094506:role/SC-882345094506-pp-jmgrxlfngaqwk-NodeInstanceRole-15Y715WVXCZYD	
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
