global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-oracle-database
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  master-defaults-12102-ol73:
    parameter_input: oracle-database-master-dataguard-12.1.0.2-ol73.json
    regions:
    - ap-northeast-1
    template_file: oracle-database-master.template
  master-defaults-12102-rhel72:
    parameter_input: oracle-database-master-dataguard-12.1.0.2-rhel72.json
    regions:
    - ap-southeast-1
    template_file: oracle-database-master.template
  master-defaults-12201-ol73:
    parameter_input: oracle-database-master-dataguard-12.2.0.1-ol73.json
    regions:
    - ap-northeast-2
    - us-east-1
    template_file: oracle-database-master.template
  master-defaults-12201-rhel72:
    parameter_input: oracle-database-master-dataguard-12.2.0.1-rhel72.json
    regions:
    - ap-southeast-2
    - ca-central-1
    template_file: oracle-database-master.template
  master-single-12102-ol73:
    parameter_input: oracle-database-master-single-12.1.0.2-ol73.json
    regions:
    - ap-northeast-2
    - eu-west-1
    template_file: oracle-database-master.template
  master-single-12102-rhel72:
    parameter_input: oracle-database-master-single-12.1.0.2-rhel72.json
    regions:
    - eu-central-1
    - eu-west-2
    template_file: oracle-database-master.template
  master-single-12201-ol73:
    parameter_input: oracle-database-master-single-12.2.0.1-ol73.json
    regions:
    - us-west-1
    - us-west-2
    template_file: oracle-database-master.template
  master-single-12201-rhel72:
    parameter_input: oracle-database-master-single-12.2.0.1-rhel72.json
    regions:
    - sa-east-1
    - us-east-2
    template_file: oracle-database-master.template
